# Generated by Django 4.0.3 on 2023-05-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_comment_modify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='modify',
        ),
        migrations.AddField(
            model_name='comment',
            name='modify',
            field=models.IntegerField(default=0),
        ),
    ]
