# Generated by Django 4.2.1 on 2023-05-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0009_remove_comment_modify_comment_modify'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='modify',
            field=models.IntegerField(default=0),
        ),
    ]
